FROM node:22-alpine3.22

RUN apk upgrade --no-cache

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN corepack enable && pnpm install --frozen-lockfile --prod

COPY . .

ENV NODE_ENV=production
EXPOSE 5000

CMD ["pnpm", "start"]
