ALTER TABLE "InboundIvrs"
  ADD COLUMN IF NOT EXISTS "scheduleEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "scheduleJson" TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS "closedAudioFile" VARCHAR(255) DEFAULT NULL;
