CREATE TABLE IF NOT EXISTS "AsteriskQueues" (
  "id" SERIAL,
  "name" VARCHAR(255) NOT NULL UNIQUE,
  "strategy" VARCHAR(50) NOT NULL DEFAULT 'ringall',
  "timeout" INTEGER NOT NULL DEFAULT 30,
  "maxlen" INTEGER NOT NULL DEFAULT 0,
  "wrapuptime" INTEGER NOT NULL DEFAULT 0,
  "musiconhold" VARCHAR(255) DEFAULT NULL,
  "announce" VARCHAR(255) DEFAULT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);
