[INCLUDES]
before = common.conf

[Definition]
_daemon = asterisk

failregex = NOTICE\[.*\].*chan_sip\.c:.*Registration from '.*' failed for '<HOST>:\d+' - Wrong password
            NOTICE\[.*\].*chan_sip\.c:.*Call from '.*' \(<HOST>:\d+\) to extension '.*' rejected because extension not found
            NOTICE\[.*\].*chan_sip\.c:.*Registration from '.*' failed for '<HOST>:\d+' - No matching peer found
            NOTICE\[.*\].*chan_sip\.c:.*Registration from '.*' failed for '<HOST>:\d+' - Username/auth name mismatch
            NOTICE\[.*\].*chan_sip\.c:.*Registration from '.*' failed for '<HOST>:\d+' - Device does not match ACL

ignoreregex =
