; pjsip_custom.conf — gerado dinamicamente pelo EdaCall backend
; Não editar manualmente — será sobrescrito pelo sistema

; BEGIN EDACALL pjsip-extension:8000
[8000](webrtc-endpoint)
auth=8000-pjsip-auth
aors=8000-pjsip

[8000-pjsip-auth](webrtc-auth)
username=8000
password=12345

[8000-pjsip](webrtc-aor)
; END EDACALL pjsip-extension:8000
