; BEGIN EDACALL sip-extension:C1-1051
[C1-1051]
type=friend
host=dynamic
secret=1234
context=default
disallow=all
allow=ulaw
allow=alaw
dtmfmode=rfc2833
nat=force_rport,comedia
directmedia=no
qualify=yes
qualifyfreq=30
; END EDACALL sip-extension:C1-1051

; BEGIN EDACALL sip-extension:2001
[2001]
type=friend
host=dynamic
secret=1234
context=default
disallow=all
allow=ulaw
allow=alaw
dtmfmode=rfc2833
nat=force_rport,comedia
directmedia=no
qualify=yes
qualifyfreq=30
; END EDACALL sip-extension:2001


; BEGIN EDACALL sip-voip-line:efix
[efix]
type=peer
host=177.124.64.158
port=5060
username=431425388
fromuser=431425388
secret=!AL5388#EFIX
context=efix
disallow=all
allow=ulaw
allow=alaw
insecure=invite,port
nat=force_rport,comedia
qualify=yes
; END EDACALL sip-voip-line:efix

; BEGIN EDACALL sip-extension:7000
[7000]
type=friend
host=dynamic
secret=$5#XDDQeqz
context=default
disallow=all
allow=ulaw
allow=alaw
dtmfmode=rfc2833
nat=force_rport,comedia
directmedia=no
qualify=yes
qualifyfreq=30
; END EDACALL sip-extension:7000

; BEGIN EDACALL sip-extension:3000
[3000]
type=friend
host=dynamic
secret=F3d*EFjhWJ
context=default
disallow=all
allow=ulaw
allow=alaw
dtmfmode=rfc2833
nat=force_rport,comedia
directmedia=no
qualify=yes
qualifyfreq=30
; END EDACALL sip-extension:3000

; BEGIN EDACALL sip-extension:1000
[1000]
type=friend
host=dynamic
secret=12345
context=default
disallow=all
allow=ulaw
allow=alaw
dtmfmode=rfc2833
nat=force_rport,comedia
directmedia=no
qualify=yes
qualifyfreq=30
; END EDACALL sip-extension:1000

; BEGIN EDACALL sip-extension:1830
[1830]
type=friend
host=dynamic
secret=1234
context=default
disallow=all
allow=ulaw
allow=alaw
dtmfmode=rfc2833
nat=force_rport,comedia
directmedia=no
qualify=yes
qualifyfreq=30
; END EDACALL sip-extension:1830

; BEGIN EDACALL sip-extension:1001
[1001]
type=friend
host=dynamic
secret=12345
context=efix
setvar=VOIPLINE=efix
disallow=all
allow=ulaw
allow=alaw
dtmfmode=rfc2833
nat=force_rport,comedia
directmedia=no
qualify=yes
qualifyfreq=30
; END EDACALL sip-extension:1001
